version: "3.8"

services:
  app:
    container_name: remotab-front
    image: express-docker
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

  backend:
    image: remotab-back
    ports:
      - 4000:4000
