version: "3.8"

services:
  app:
    container_name: remotab-front
    image: remotab-front
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000